name: hr_attendance_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  provider: ^6.1.5+1
  intl: ^0.19.0
  image_picker: ^1.2.0
  mask_text_input_formatter: ^2.9.0
  animated_item: ^0.0.2
  path: ^1.9.1
  path_provider: ^2.1.5
  http: ^1.5.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.12
  supabase_flutter: ^2.10.1
  flutter_dotenv: ^5.2.1
  camera: ^0.11.2
  geolocator: ^12.0.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/
    - assets/img/profile.jpg
    - assets/img/logo-noimage.png
